### ISSUE TITLE
Зеркало и региональный блок

### ISSUE THREAD

**Issue by elpaxel** [falcofemoralis/HDrezka-app#104]
Здравствуйте.
Сразу скажу что очень благодарен за удобное приложение и прошу прощения за наглость.

Я предполагаю что "hdrzk.org" это созданное вами зеркало (прокси). Так же предполагаю что находится оно на хостинге "alexhost", а значит расположено в Молдове. Следовательно, регионального блока на Резке не должно быть, но он есть.
Если это не ваше зеркало или снятие регионального блока не было целью тогда никаких претензий.
В противном случае могу предположить что прокси настроена неправильно.

**Comment by falcofemoralis** [comment]
Здравствуйте. Это не мое зеркало)
